# utils/help_manager.py

HELP_DATA = {
    "ZONE 1 | STRUCTURAL DISCOVERY (Pre-Processing)": {
        "--100": {
            "desc": "Converts structural data into a core data template.",
            "prereq": "A valid crystal structure file (e.g., .cif)",
            "output": "scf.dat (Core template containing structural blocks)"
        },
        "--101": {
            "desc": "Validates and links pseudopotentials to your structural template.",
            "prereq": "scf.dat (Generated by Module 100)",
            "output": "Updates scf.dat with real UPF filenames and targets pseudo_dir"
        },
        "--102": {
            "desc": "Generates high-symmetry K-point paths for dispersion calculations.",
            "prereq": "scf.dat (With validated crystal parameters)",
            "output": "Appends explicit K-point path coordinates to scf.dat"
        }
    },
    "ZONE 2 | INPUT FILE ARCHITECT (Binary Setup)": {
        "--200": {
            "desc": "Generates execution-ready Ground-State SCF input.",
            "prereq": "scf.dat (With matched pseudopotentials)",
            "output": "scf.in (Input block for pw.x execution)"
        },
        "--201": {
            "desc": "Generates Variable-Cell Structural Optimization input.",
            "prereq": "scf.dat",
            "output": "vc-relax.in (Input block for structural relaxation)"
        },
        "--202": {
            "desc": "Generates dense, unshifted grid NSCF input.",
            "prereq": "scf.dat + Successful converged ground-state calculation",
            "output": "nscf.in (Required for highly accurate DOS/Fermi Surface calculations)"
        },
        "--203": {
            "desc": "Generates input for atomic projected density of states calculations.",
            "prereq": "nscf output files in outdir/",
            "output": "projwfc.in (Input block for projwfc.x)"
        },
        "--204": {
            "desc": "Generates input for electronic band dispersion paths.",
            "prereq": "Converged ground-state calculations",
            "output": "bands.in (Input block for bands.x)"
        },
        "--205": {
            "desc": "Generates input for optical properties calculations.",
            "prereq": "Dense NSCF grid output",
            "output": "epsilon.in (Input block for epsilon.x)"
        },
        "--206": {
            "desc": "Generates input for Density Functional Perturbation Theory (DFPT) phonon runs.",
            "prereq": "Successful converged ground-state SCF calculation",
            "output": "ph.in (Input block for ph.x lattice dynamics execution)"
        },
        "--207": {
            "desc": "Generates Fermi Surface extraction grids. Runs XML health checks first.",
            "prereq": "Successful dense, unshifted grid NSCF calculation",
            "output": "fs.in (Input block for fs.x execution)"
        },
        "--208": {
            "desc": "Generates elastic/thermo driver input. Runs XML status checks first.",
            "prereq": "Successful converged ground-state SCF run",
            "output": "thermo_control (Input configuration driver for thermo_pw.x)"
        }
    },
    "ZONE 3 | POST-PROCESSING (Data Extraction)": {
        "--300": {
            "desc": "Refines lattice parameters and handles cell2ibrav mapping after geometry optimization.",
            "prereq": "vc-relax.out (Containing optimized final atomic configurations)",
            "output": "Prints clean crystalline matrices; updates scf.dat variables"
        },
        "--301": {
            "desc": "Processes interatomic force constants into plottable phonon dispersion arrays.",
            "prereq": "Raw ph.x output matrices",
            "output": "Clean data arrays optimized for band/phonon plotters"
        },
        "--302": {
            "desc": "Sums individual orbital contributions to yield total system PDOS data.",
            "prereq": "Raw projwfc.x output fragments",
            "output": "Aggregated spectral arrays optimized for graphing"
        },
        "--303": {
            "desc": "Extracts dielectric functions and derives macroscopic optical constants.",
            "prereq": "Raw epsilon.x structural matrices",
            "output": "Reflectivity, absorption coefficient, and refractive index arrays"
        },
        "--304": {
            "desc": "Calculates isotropic electron-phonon coupling matrices and maps superconducting parameters.",
            "prereq": "Completed Eliashberg function (alpha2F) output data",
            "output": "Prints critical temperature (Tc), lambda parameter, and log-average frequency"
        },
        "--305": {
            "desc": "Parses dynamic thermodynamic logs, strain tensors, and elastic compliance states.",
            "prereq": "Completed thermo_pw.x output logs",
            "output": "result.txt (VRH averages, Debye Temp, applied strains, symmetric GPa matrix)"
        }
    },
    "ZONE 4 | DATA VISUALIZATION (Graphical Rendering)": {
        "--401": {
            "desc": "Launches automated pipeline sequence to drive high-throughput calculation loops.",
            "prereq": "Configured environment tools",
            "output": "Drives parallel background calculation suites via Bash wrapper"
        },
        "--402": {
            "desc": "Plots overlaid datasets to compare electronic/phononic modifications directly.",
            "prereq": "Processed data arrays",
            "output": "Launches interactive/saved graphics rendering via Gnuplot"
        },
        "--403": {
            "desc": "Generates stacked multi-panel grid plots (e.g., matching Bands alongside DOS).",
            "prereq": "Processed data arrays",
            "output": "Launches synchronized layout windows via Gnuplot"
        },
        "--404": {
            "desc": "Calculates and maps reciprocal space boundaries to build interactive crystal nodes.",
            "prereq": "Reciprocal lattice vectors derived from crystal structural data",
            "output": "Renders interactive 3D Brillouin Zone maps via Matplotlib"
        },
        "--405": {
            "desc": "Computes theoretical X-Ray diffraction patterns from atomic positions.",
            "prereq": "Crystal structural configurations (scf.dat or .cif)",
            "output": "Calculates structure factors and renders simulated spectral peaks via Pymatgen"
        }
    }
}

def display_help():
    """Renders an explanatory, production-ready terminal dashboard."""
    print("\n" + "=" * 85)
    print("   QE-Kit | Advanced Headless CLI Reference Manual")
    print("   Syntax: python3 qekit.py --<MODULE_ID>")
    print("=" * 85)
    
    for zone, modules in HELP_DATA.items():
        print(f"\n📁 {zone}")
        print("─" * len(zone))
        
        for flag, info in modules.items():
            print(f"  \033[1;32m{flag:<6}\033[0m : {info['desc']}")
            print(f"           \033[1;33m[Prereq]:\033[0m {info['prereq']}")
            print(f"           \033[1;36m[Yields]:\033[0m {info['output']}")
            print("  " + "─" * 75)
            
    print("\n" + "=" * 85 + "\n")

if __name__ == "__main__":
    display_help()
